name: wag_wordsaregold
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  numberpicker: ^2.1.2
  syncfusion_flutter_charts: ^28.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagen1.png
    - assets/imagen2.png
    - assets/imagen3.png
    - assets/imagen4.png
    - assets/imagen5.png
    - assets/imagen6.png
    - assets/imagen7.png
    - assets/imagen8.png
    - assets/logo.png
    - assets/logo2.png
    - assets/google_logo.png

